### ISSUE TITLE
concat::fragment $ensure deprecated

### ISSUE THREAD

**Issue by strarsis** [jfryman/puppet-nginx#802] opened 2016-05-02 14:04 UTC
````
The $ensure parameter to concat::fragment is deprecated and has no effect.
````
So the $ensure parameters could be now safely removed 
from concat::fragment ressources in this module?

Thanks and 
with best regards

**Comment by 3flex** [comment] 2016-05-02 14:11
Duplicate of https://github.com/jfryman/puppet-nginx/issues/759

Will be fixed in the next Forge release.

**Closed by 3flex** 2016-05-02 14:11 UTC

**Comment by pcarrilloj** [comment] 2016-06-23 16:11
When will be released this change?
