### ISSUE TITLE
vhost configuration, www_root and default location

### ISSUE THREAD

**Issue by edvinasme** [jfryman/puppet-nginx#317] opened 2014-05-18 12:33 UTC
The vhost configuration files that are generated by puppet are sometimes not according to the best practices and sometimes even follow nginx configuration pitfalls ( http://wiki.nginx.org/Pitfalls ). Before I start fixing and filing a PR for this I would first like to discuss if there are any reasons for why this currently works as it does.

The problem that I see and would like to fix:
1. We ALWAYS have multiple declarations of `root` (inside all locations, but the `server` directive never has one).

I would propose including `root` in `resource::vhost` would make it appear in `server directive`. We could still define a `location /`, but then it would not need `root` defined in it. For `recource::location` if `www_root` in `resource::location` is relative to vhost's `www_root`, we can skip it.

I would also propose introducing a parameter which would let you skip default `location /` declaration if needed. This is extremely useful when you only want to define a vhost for redirecting to another vhost, thus you do not even need any locations defined.

Can I start working on changes, please tell me what you think.

**Comment by kdfreeheart** [comment] 2015-01-14 21:03
+1 to this. 

Using this module with Owncloud is kind of painful, as it requires the root to be specified inside of the server block and fails to load if root is specified in location /.

Saner behavior, I think, would be using www_root to set root in the server block, as described in the Pitfalls document.

A new (optional) parameter, location_root, should be applied to individual location resources if set. If not, simply don't set it, as it's not required.

**Comment by 3flex** [comment] 2015-04-13 21:22
This is a duplicate of #142, so I'm closing this in favour of that issue. Please add your +1 there if you feel it's appropriate.

**Closed by 3flex** 2015-04-13 21:22 UTC
