### ISSUE TITLE
key and cert are required under SSL

### ISSUE THREAD

**Issue by gerases** [jfryman/puppet-nginx#793] opened 2016-04-02 13:56 UTC
This makes the catalog fail:
    
```
if ($ssl == true) {
      if ($ssl_cert == undef) or ($ssl_key == undef) {
          fail('nginx: SSL certificate/key (ssl_cert/ssl_key) and/or SSL Private must be defined and exist on the tar  get system(s)')
      }
    }
```

But in my case (and it's hard to change due to various reasons), we provide the key and the cert in an include.

Maybe the solution is to define an array param that will say, "hey, don't validate these params because they are defined elsewhere"?

For now, I have to comment out that validation block :(

Another option is to have a param called something like 'ssl_strict_validate' and default it to true?

**Comment by 3flex** [comment] 2016-04-11 14:31
This is a duplicate of your issue #743

**Closed by 3flex** 2016-04-11 14:31 UTC
